version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # run test
     - run: cd web; yarn test
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/walklog_db db
     - run: docker build -t $DOCKER_USER/walklog_web web

     # deploy the image
     - run: docker push $DOCKER_USER/walklog_db
     - run: docker push $DOCKER_USER/walklog_web