version: '2'
services:
  db:
    restart: always
    build: .
    volumes:
      - data:/var/lib/postgresql/data
  web:
    restart: always
    build: web
    volumes:
      - public:/var/www/public
    ports:
      - 3000:3000
    links:
      - db:walklog

volumes:
  data:
  public:
