name: ci
on: pull_request
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v7
    - name: Setup Vite+ and install dependencies
      uses: voidzero-dev/setup-vp@v1.21.1
      with:
        node-version: '24'
        working-directory: web
        cache: true
    - name: run lint, formatter and typecheck
      run: vp check
    - name: run test
      run: vp run test
    - name: Upload coverage report
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: web
