name: ci
on: pull_request
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24.x'
    - name: pnpm-setup
      uses: pnpm/action-setup@v6
      with:
        version: 10
        run_install: true
    - name: run typecheck
      run: pnpm typecheck
    - name: run eslint
      run: pnpm lint
    - name: run test
      run: pnpm test
    - name: Upload coverage report
      if: always()
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: web
