allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@5.0.3'
  - '@vitest/mocker@5.0.3'
  - '@vitest/pretty-format@5.0.3'
  - '@vitest/spy@5.0.3'
  - '@vitest/ui@5.0.3'
  - '@vitest/utils@5.0.3'
  - vitest@5.0.3
