allowBuilds:
  "@firebase/util": true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 5.0.1
  vite-plus: 1.0.0
  "@vitest/coverage-v8": 5.0.1
  "@vitest/ui": 5.0.1
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
